---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
TASK Lab 1 :
Chapter 10 Lab 1: Principal Components Analysis

```{r include=FALSE}
states=row.names(USArrests )
states  
```

```{r}
names(USArrests)
```

```{r }
apply(USArrests, 2, mean)

```

```{r}
apply(USArrests, 2, var)
```

```{r}
pr.out=prcomp(USArrests, scale=TRUE)
```


```{r}
names(pr.out)
```

```{r}
pr.out$center
```

```{r}
pr.out$scale
```

```{r}
pr.out$rotation
```

```{r}
dim(pr.out$x)
```

```{r}
biplot (pr.out , scale =0)
```

```{r}
pr.out$rotation=-pr.out$rotation
pr.out$x=-pr.out$x
biplot(pr.out, scale=0)
```

```{r}
pr.out$sdev
```

```{r}
pr.var=pr.out$sdev^2
pr.var
```

```{r}
pve=pr.var/sum(pr.var)
pve
```

```{r}
plot(pve, xlab="Principal Component", ylab="Proportion of Variance Explained", ylim=c(0,1),type='b')

```

```{r}
plot(cumsum(pve), xlab="Principal Component", ylab="Cumulative Proportion of Variance Explained", ylim=c(0,1),type='b')
```

```{r}
a=c(1,2,8,-3)
cumsum(a)
```




